
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Oct 30 2025 17:26:52 IST (Oct 30 2025 11:56:52 UTC)

// Verification Directory fv/weighted_rr_arbiter 

module weighted_rr_arbiter(clk, reset_n, request, weights, grant);
  input clk, reset_n;
  input [3:0] request;
  input [15:0] weights;
  output [3:0] grant;
  wire clk, reset_n;
  wire [3:0] request;
  wire [15:0] weights;
  wire [3:0] grant;
  wire [3:0] grant_fsm_inst_weight_count;
  wire [3:0] ngprc_inst_priority_mask;
  wire [3:0] next_grant_mask;
  wire [3:0] grant_fsm_inst_current_grant;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, n_1, n_2,
       n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_19, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_36, n_37, n_38, n_39;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_79;
  wire n_80, n_81;
  DFFRHQX1 \grant_fsm_inst_weight_count_reg[0] (.RN (reset_n), .CK
       (clk), .D (n_56), .Q (grant_fsm_inst_weight_count[0]));
  DFFRHQX1 \grant_fsm_inst_weight_count_reg[1] (.RN (reset_n), .CK
       (clk), .D (n_55), .Q (grant_fsm_inst_weight_count[1]));
  DFFRHQX1 \grant_fsm_inst_weight_count_reg[2] (.RN (reset_n), .CK
       (clk), .D (n_53), .Q (grant_fsm_inst_weight_count[2]));
  AOI2BB1XL g1456__2398(.A0N (n_50), .A1N
       (grant_fsm_inst_weight_count[1]), .B0
       (grant_fsm_inst_weight_count[0]), .Y (n_56));
  OAI221XL g1457__5107(.A0 (n_49), .A1 (n_54), .B0 (n_38), .B1 (n_54),
       .C0 (n_3), .Y (n_55));
  DFFRHQX1 \grant_fsm_inst_weight_count_reg[3] (.RN (reset_n), .CK
       (clk), .D (n_51), .Q (grant_fsm_inst_weight_count[3]));
  OAI222XL g1459__6260(.A0 (n_45), .A1 (n_52), .B0 (n_8), .B1 (n_7),
       .C0 (n_52), .C1 (n_43), .Y (n_53));
  OAI211XL g1461__4319(.A0 (n_41), .A1 (n_36), .B0 (n_79), .C0 (n_13),
       .Y (n_51));
  NAND3X1 g1463__8428(.A (n_39), .B (n_46), .C (n_5), .Y (n_50));
  AOI221X1 g1465__5526(.A0 (weights[1]), .A1 (n_47), .B0 (weights[13]),
       .B1 (n_42), .C0 (n_6), .Y (n_49));
  AOI22X1 g1469__3680(.A0 (weights[0]), .A1 (n_47), .B0 (weights[4]),
       .B1 (n_44), .Y (n_46));
  AOI22X1 g1470__1617(.A0 (weights[2]), .A1 (n_47), .B0 (weights[6]),
       .B1 (n_44), .Y (n_45));
  AOI221X1 g1471__2802(.A0 (weights[10]), .A1 (n_81), .B0
       (weights[14]), .B1 (n_42), .C0 (grant_fsm_inst_weight_count[3]),
       .Y (n_43));
  AOI222X1 g1472__1705(.A0 (weights[7]), .A1 (n_44), .B0 (weights[11]),
       .B1 (n_81), .C0 (weights[15]), .C1 (n_42), .Y (n_41));
  AOI22X1 g1477__5122(.A0 (weights[8]), .A1 (n_81), .B0 (weights[12]),
       .B1 (n_42), .Y (n_39));
  AOI22X1 g1473__8246(.A0 (weights[5]), .A1 (n_44), .B0 (weights[9]),
       .B1 (n_81), .Y (n_38));
  DFFSX1 \ngprc_inst_priority_mask_reg[3] (.SN (reset_n), .CK (clk), .D
       (n_37), .Q (ngprc_inst_priority_mask[3]), .QN (UNCONNECTED));
  DFFSX1 \ngprc_inst_priority_mask_reg[2] (.SN (reset_n), .CK (clk), .D
       (n_34), .Q (ngprc_inst_priority_mask[2]), .QN (UNCONNECTED0));
  DFFRHQX1 \ngprc_inst_next_grant_mask_reg[1] (.RN (reset_n), .CK
       (clk), .D (n_31), .Q (next_grant_mask[1]));
  NOR4BX1 g1480__7098(.AN (grant[0]), .B (n_80), .C (grant[1]), .D
       (grant[2]), .Y (n_47));
  OAI211XL g1462__6131(.A0 (n_33), .A1 (grant[2]), .B0 (n_27), .C0
       (n_32), .Y (n_37));
  DFFRHQX1 \ngprc_inst_next_grant_mask_reg[3] (.RN (reset_n), .CK
       (clk), .D (n_29), .Q (next_grant_mask[3]));
  DFFRHQX1 \ngprc_inst_next_grant_mask_reg[2] (.RN (reset_n), .CK
       (clk), .D (n_30), .Q (next_grant_mask[2]));
  DFFRHQX1 \ngprc_inst_next_grant_mask_reg[0] (.RN (reset_n), .CK
       (clk), .D (n_28), .Q (next_grant_mask[0]));
  SDFFRHQX1 \grant_fsm_inst_current_grant_reg[2] (.RN (reset_n), .CK
       (clk), .D (n_11), .SI (grant_fsm_inst_current_grant[2]), .SE
       (n_36), .Q (grant_fsm_inst_current_grant[2]));
  SDFFRHQX1 \grant_fsm_inst_current_grant_reg[3] (.RN (reset_n), .CK
       (clk), .D (n_14), .SI (grant_fsm_inst_current_grant[3]), .SE
       (n_36), .Q (grant_fsm_inst_current_grant[3]));
  SDFFRHQX1 \grant_fsm_inst_current_grant_reg[1] (.RN (reset_n), .CK
       (clk), .D (n_2), .SI (grant_fsm_inst_current_grant[1]), .SE
       (n_36), .Q (grant_fsm_inst_current_grant[1]));
  SDFFRHQX1 \grant_fsm_inst_current_grant_reg[0] (.RN (reset_n), .CK
       (clk), .D (next_grant_mask[0]), .SI
       (grant_fsm_inst_current_grant[0]), .SE (n_36), .Q
       (grant_fsm_inst_current_grant[0]));
  DFFSX1 \ngprc_inst_priority_mask_reg[1] (.SN (reset_n), .CK (clk), .D
       (n_21), .Q (ngprc_inst_priority_mask[1]), .QN (UNCONNECTED1));
  NOR3X1 g1489__5115(.A (n_80), .B (n_1), .C (grant[2]), .Y (n_44));
  OAI21XL g1467__7482(.A0 (n_33), .A1 (n_17), .B0 (n_32), .Y (n_34));
  INVXL g1490(.A (n_26), .Y (n_31));
  INVXL g1494(.A (n_25), .Y (n_30));
  INVXL g1495(.A (n_22), .Y (n_29));
  INVXL g1496(.A (n_23), .Y (n_28));
  NAND2X1 g1466__4733(.A (n_33), .B (grant[2]), .Y (n_27));
  OAI21XL g1492__6161(.A0 (n_24), .A1 (ngprc_inst_priority_mask[1]),
       .B0 (request[1]), .Y (n_26));
  OAI21XL g1497__9315(.A0 (n_24), .A1 (ngprc_inst_priority_mask[2]),
       .B0 (request[2]), .Y (n_25));
  OAI21XL g1499__9945(.A0 (n_24), .A1 (ngprc_inst_priority_mask[0]),
       .B0 (request[0]), .Y (n_23));
  OAI21XL g1498__2883(.A0 (n_24), .A1 (ngprc_inst_priority_mask[3]),
       .B0 (request[3]), .Y (n_22));
  NAND2BXL g1485__2346(.AN (n_15), .B (n_32), .Y (n_21));
  DFFSX1 \ngprc_inst_priority_mask_reg[0] (.SN (reset_n), .CK (clk), .D
       (n_12), .Q (ngprc_inst_priority_mask[0]), .QN (UNCONNECTED2));
  NOR2X1 g1507__7410(.A (n_24), .B (n_19), .Y (n_42));
  NOR2BX1 g1486__6417(.AN (grant[1]), .B (n_16), .Y (n_17));
  NOR2BX1 g1488__5477(.AN (n_16), .B (grant[1]), .Y (n_33));
  AOI21XL g1504__2398(.A0 (grant[3]), .A1 (grant[0]), .B0 (n_16), .Y
       (n_15));
  NOR2XL g1505__5107(.A (n_10), .B (next_grant_mask[2]), .Y (n_14));
  NAND2X1 g1501__6260(.A (n_52), .B (grant_fsm_inst_weight_count[3]),
       .Y (n_13));
  OR2X2 g1503__4319(.A (n_52), .B (grant_fsm_inst_weight_count[3]), .Y
       (n_36));
  NOR3X1 g1513__8428(.A (n_4), .B (next_grant_mask[3]), .C
       (next_grant_mask[2]), .Y (n_24));
  NAND2XL g1491__5526(.A (n_19), .B (n_32), .Y (n_12));
  AND2X2 g1511__6783(.A (n_9), .B (next_grant_mask[2]), .Y (n_11));
  NAND2X1 g1512__3680(.A (n_9), .B (next_grant_mask[3]), .Y (n_10));
  NOR2X1 g1508__1617(.A (grant[3]), .B (grant[0]), .Y (n_16));
  NAND2X1 g1509__2802(.A (n_8), .B (n_7), .Y (n_52));
  INVX1 g1518(.A (n_5), .Y (n_6));
  INVX1 g1519(.A (n_9), .Y (n_4));
  INVX1 g1520(.A (n_8), .Y (n_54));
  OR4X2 g1506__1705(.A (ngprc_inst_priority_mask[1]), .B
       (ngprc_inst_priority_mask[0]), .C (ngprc_inst_priority_mask[3]),
       .D (ngprc_inst_priority_mask[2]), .Y (n_32));
  NAND2X1 g1522__5122(.A (grant_fsm_inst_weight_count[0]), .B
       (grant_fsm_inst_weight_count[1]), .Y (n_3));
  NOR2BXL g1521__8246(.AN (next_grant_mask[1]), .B
       (next_grant_mask[0]), .Y (n_2));
  NOR2X1 g1524__7098(.A (next_grant_mask[0]), .B (next_grant_mask[1]),
       .Y (n_9));
  DFFRHQX1 \grant_fsm_inst_grant_reg[0] (.RN (reset_n), .CK (clk), .D
       (grant_fsm_inst_current_grant[0]), .Q (grant[0]));
  NOR2X1 g1523__6131(.A (grant_fsm_inst_weight_count[3]), .B
       (grant_fsm_inst_weight_count[2]), .Y (n_5));
  NOR2X1 g1525__1881(.A (grant_fsm_inst_weight_count[0]), .B
       (grant_fsm_inst_weight_count[1]), .Y (n_8));
  DFFRHQX1 \grant_fsm_inst_grant_reg[3] (.RN (reset_n), .CK (clk), .D
       (grant_fsm_inst_current_grant[3]), .Q (grant[3]));
  DFFRHQX1 \grant_fsm_inst_grant_reg[1] (.RN (reset_n), .CK (clk), .D
       (grant_fsm_inst_current_grant[1]), .Q (grant[1]));
  DFFRHQX1 \grant_fsm_inst_grant_reg[2] (.RN (reset_n), .CK (clk), .D
       (grant_fsm_inst_current_grant[2]), .Q (grant[2]));
  INVX1 g1528(.A (grant[1]), .Y (n_1));
  INVX1 g1526(.A (grant[3]), .Y (n_19));
  INVX1 g1527(.A (grant_fsm_inst_weight_count[2]), .Y (n_7));
  NAND3BX1 g2(.AN (n_36), .B (weights[3]), .C (n_47), .Y (n_79));
  NAND2BX1 g1550(.AN (n_24), .B (n_19), .Y (n_80));
  NOR2BX1 g1551(.AN (grant[2]), .B (n_80), .Y (n_81));
endmodule

